name: bass
version: 0.1.0
author: Alexander Adeniyin Ewetumo <trinoxf@gmail.com>
homepage: http://github.com/influx6/bass.dart
description: a derivative css processor based on dart syntax (following the AbsurdJS style) 
dependencies:
    hub: any
# dependency_overrides:
#    hub:
#      path: ../hub
